#!/usr/bin/env python3
"""Regenerate bimandbeam.com's Yoast-era sitemap files for the static export.

Fixes (see bimandbeam.com-audit/findings/sitemap.md for the full audit):
  1. All <loc> values were relative ("./blog/") instead of absolute
     (https://bimandbeam.com/blog/), violating the sitemaps.org protocol.
  2. post-sitemap.xml was stale: missing the newest posts, and carried
     3 dead/mangled entries for renamed or nonexistent slugs.

What this script does:
  - post-sitemap.xml: fully regenerated by walking YYYY/MM/slug/index.html
    directories in the repo (the actual source of truth), so it can never
    drift from what's really published. lastmod comes from git history
    (falls back to file mtime if a path has no git history yet, e.g. a
    brand-new uncommitted post).
  - page-sitemap.xml, category-sitemap.xml, post_tag-sitemap.xml,
    author-sitemap.xml, sitemap_index.xml: content was already verified
    accurate by the audit, so these are only rewritten in place to turn
    every relative <loc>/<image:loc> into an absolute URL. sitemap_index.xml
    additionally gets its post-sitemap.xml <lastmod> bumped to "now".

Run this after adding, renaming, or removing any post directory, before
pushing to GitHub Pages:

    python scripts/generate_sitemaps.py

(A GitHub Action that runs this automatically on push would remove the
"remember to run it" step entirely -- see the audit's recommendation.)
"""
from __future__ import annotations

import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://bimandbeam.com"

# Known dead/renamed sitemap entries the audit found -- explicitly listed so
# a future re-run never silently reintroduces them if some other tool writes
# a stale entry back.
DEAD_SLUGS = {
    "2021/09/bim workflow-vs-cad-workflow-html",
    "2021/09/bim rolesandresponsibilities -html",
    "2025/04/difference-bim-manager-revit-manager",
}

YEAR_RE = re.compile(r"^\d{4}$")
MONTH_RE = re.compile(r"^\d{2}$")


def git_lastmod(path: Path) -> datetime | None:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cI", "--", str(path.relative_to(ROOT))],
            cwd=ROOT, capture_output=True, text=True, check=True, timeout=10,
        ).stdout.strip()
    except Exception:
        return None
    if not out:
        return None
    return datetime.fromisoformat(out)


def lastmod_for(path: Path) -> str:
    dt = git_lastmod(path)
    if dt is None:
        dt = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    return dt.astimezone(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "+00:00")


def discover_posts() -> list[tuple[str, Path]]:
    """Return (url_path, index.html path) for every real post directory."""
    posts = []
    for year_dir in sorted(ROOT.iterdir()):
        if not year_dir.is_dir() or not YEAR_RE.match(year_dir.name):
            continue
        for month_dir in sorted(year_dir.iterdir()):
            if not month_dir.is_dir() or not MONTH_RE.match(month_dir.name):
                continue
            for slug_dir in sorted(month_dir.iterdir()):
                index = slug_dir / "index.html"
                if not slug_dir.is_dir() or not index.is_file():
                    continue
                url_path = f"{year_dir.name}/{month_dir.name}/{slug_dir.name}"
                if url_path in DEAD_SLUGS:
                    continue
                posts.append((url_path, index))
    return posts


def build_post_sitemap() -> str:
    entries = []

    blog_index = ROOT / "blog" / "index.html"
    entries.append(("blog", blog_index))
    entries.extend(discover_posts())

    # Newest first -- more useful ordering for a human/bot skimming the file
    # than the arbitrary Yoast-internal order it previously had.
    dated = [(url_path, lastmod_for(path)) for url_path, path in entries]
    dated.sort(key=lambda item: item[1], reverse=True)

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<?xml-stylesheet type="text/xsl" href="https://bimandbeam.com/main-sitemap.xsl"?>',
        '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" '
        'xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 '
        'http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd '
        'http://www.google.com/schemas/sitemap-image/1.1 '
        'http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" '
        'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for url_path, lastmod in dated:
        loc = f"{BASE_URL}/{url_path}/" if url_path != "blog" else f"{BASE_URL}/blog/"
        lines.append(f"\t<url>\n\t\t<loc>{loc}</loc>\n\t\t<lastmod>{lastmod}</lastmod>\n\t</url>")
    lines.append("</urlset>")
    lines.append("<!-- XML Sitemap generated by scripts/generate_sitemaps.py -->")
    return "\n".join(lines) + "\n"


def rewrite_relative_urls(xml_text: str) -> str:
    xml_text = re.sub(r"(<loc>)\./", rf"\1{BASE_URL}/", xml_text)
    xml_text = re.sub(r"(<image:loc>)\./", rf"\1{BASE_URL}/", xml_text)
    xml_text = re.sub(
        r'(href=")\./main-sitemap\.xsl(")', rf"\1{BASE_URL}/main-sitemap.xsl\2", xml_text
    )
    return xml_text


def bump_post_sitemap_lastmod(sitemap_index_text: str) -> str:
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    def _replace(match: re.Match) -> str:
        block = match.group(0)
        return re.sub(r"<lastmod>[^<]*</lastmod>", f"<lastmod>{now}</lastmod>", block)

    return re.sub(
        r"<sitemap>\s*<loc>[^<]*post-sitemap\.xml</loc>.*?</sitemap>",
        _replace,
        sitemap_index_text,
        flags=re.S,
    )


def main() -> None:
    post_sitemap_path = ROOT / "post-sitemap.xml"
    new_post_sitemap = build_post_sitemap()
    post_sitemap_path.write_text(new_post_sitemap, encoding="utf-8")
    n_urls = new_post_sitemap.count("<url>")
    print(f"post-sitemap.xml regenerated: {n_urls} URLs, all absolute.")

    for name in ("page-sitemap.xml", "category-sitemap.xml", "post_tag-sitemap.xml", "author-sitemap.xml"):
        path = ROOT / name
        text = path.read_text(encoding="utf-8")
        fixed = rewrite_relative_urls(text)
        path.write_text(fixed, encoding="utf-8")
        print(f"{name}: relative URLs rewritten to absolute.")

    index_path = ROOT / "sitemap_index.xml"
    index_text = index_path.read_text(encoding="utf-8")
    index_text = rewrite_relative_urls(index_text)
    index_text = bump_post_sitemap_lastmod(index_text)
    index_path.write_text(index_text, encoding="utf-8")
    print("sitemap_index.xml: relative URLs rewritten to absolute, post-sitemap.xml lastmod bumped.")

    root_sitemap_path = ROOT / "sitemap.xml"
    if root_sitemap_path.is_file():
        text = root_sitemap_path.read_text(encoding="utf-8")
        root_sitemap_path.write_text(rewrite_relative_urls(text), encoding="utf-8")
        print("sitemap.xml: relative URLs rewritten to absolute.")


if __name__ == "__main__":
    main()
